spring:
  profiles:
    active: dev
  application:
    name: eco
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # OBS: Verificar nome do banco e a porta correta
    url: jdbc:mysql://localhost:3306/eco?useTimezone=true&serverTimezone=UTC
    username: root
    # OBS: Substituir pela senha real
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    # todos os pacotes
    root: INFO
    # pacote espec√≠fico
    com.example.ecoguardian: DEBUG
